### ISSUE TITLE
"MIT" License mentioned in README.md

### ISSUE THREAD

**Issue by m-ueberall** [thegeeklab/drone-matrix#12]
Not sure whether [the last sentence in the README](https://github.com/thegeeklab/drone-matrix/blob/0b8d6ffabcf2e73cf2dcac0a59f3c04afad85400/README.md?plain=1#L22) mentioning the ["MIT"](https://spdx.org/licenses/MIT.html) licence is wrong or whether it is supposed to express that either the Apache-2.0 and/or the MIT licence applies. The referenced [`LICENSE`](https://github.com/thegeeklab/drone-matrix/blob/main/LICENSE) file definitely only contains the former.

**Comment by xoxys** [comment]
Thanks for the hint, that's a copy and paste issue.
