### ISSUE TITLE
MsgType should be text instead of notice

### ISSUE THREAD

**Issue by hobbypunk90** [thegeeklab/drone-matrix#28]
Hello,

i'm not sure, but it seams that notice is the wrong message type, i never get any notifications.
The build message appears completely silent in the room.

Greets
Marcel

**Comment by xoxys** [comment]
Hi, I would need some more information. Im using the plugin on a daily basis on my own and  have not seen this issue yet. What room version do you use? Is the room unencrypted?

**Comment by hobbypunk90** [comment]
@xoxys room version 9 and it's unencrypted. And i "fixed" it :man_facepalming: i totally missed that there are different settings for encrypted and unencrypted rooms, sorry for that :see_no_evil:
